force-app/main/default/objects/Championship__c/Championship__c.object-meta.xml
<CustomObject>
    <description>Championship information</description>
    <label>Championship</label>
    <nameField>
        <label>Championship  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Championship__c/fields/Championship_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Championship_Capacity__c</fullName>
    <label>Championship Capacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Championship__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <description>Write the location of the championship</description>
    <inlineHelpText>Write the location of the championship</inlineHelpText>
    <label>Track</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Racer__c/Racer__c.object-meta.xml
<CustomObject>
    <description>Racer members</description>
    <label>Racer</label>
    <nameField>
        <label>Racer Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer_Position__c/Racer_Position__c.object-meta.xml
<CustomObject>
    <description>Racer position on championship</description>
    <label>Racer Position</label>
    <nameField>
        <label>Racer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer_Position__c/fields/Championship__c.field-meta.xml
<CustomField>
    <fullName>Championship__c</fullName>
    <description>Select championship</description>
    <inlineHelpText>Select championship</inlineHelpText>
    <label>Championship</label>
    <referenceTo>Championship__c</referenceTo>
    <relationshipLabel>Racer Positions</relationshipLabel>
    <relationshipName>Championship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Experience_in_championship_track__c.field-meta.xml
<CustomField>
    <fullName>Experience_in_championship_track__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Experience in championship track</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <description>Select racer</description>
    <inlineHelpText>Select racer</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Racer__c</referenceTo>
    <relationshipLabel>Racer Positions</relationshipLabel>
    <relationshipName>Racer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RacerExperienceOnTrackHelper.cls
public with sharing class RacerExperienceOnTrackHelper {
    public static void checkExperienceOnTrack(Map<Id, Racer_Position__c> racers) {
        List <Racer_Position__c> allRacers =  [ SELECT Name, Racer__c, Championship__c, Creation_Date__c FROM Racer_Position__c ];
        List <Championship__c>  champs = [ SELECT Name, Track__c, Championship_Capacity__c FROM Championship__c ];
        List<Racer_Position__c> forUpdate = new List<Racer_Position__c>();

        Map <String, Racer_Position__c> trackRacer = new Map <String, Racer_Position__c>();
        Map <String, Racer_Position__c> incomingTackRacer = new Map <String, Racer_Position__c>();

        for (Championship__c c : champs) {
            for (Racer_Position__c r : allRacers) {
                if(c.Id==r.Championship__c){
                    //System.debug('Racer: '+r);
                    trackRacer.put(c.Track__c, r);
                }
                
            }
        }
        
        //System.debug('TRACK:'+trackRacer);
        for (Racer_Position__c r : racers.values()) {
            for (Championship__c c : champs) {
                if(c.Id==r.Championship__c){
                    incomingTackRacer.put(c.Track__c, r);
                }
            }
        }
       
        for (String r : incomingTackRacer.keySet()) {
            for (String r2 : trackRacer.keySet()) {
                if (r==r2) {
                    System.debug('Inc '+incomingTackRacer.get(r));
                    Racer_Position__c updRacer=incomingTackRacer.get(r);
                    updRacer.Experience_in_championship_track__c=true;
                    forUpdate.add(updRacer);
             
                }
            }
        }
   
        update forUpdate;
    }
}