force-app/main/default/objects/Championship__c/Championship__c.object-meta.xml
<CustomObject>
    <description>Championship information</description>
    <label>Championship</label>
    <nameField>
        <label>Championship  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Championship__c/fields/Championship_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Championship_Capacity__c</fullName>
    <label>Championship Capacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/Racer_Position__c.object-meta.xml
<CustomObject>
    <description>Racer position on championship</description>
    <label>Racer Position</label>
    <nameField>
        <label>Racer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer_Position__c/fields/Championship__c.field-meta.xml
<CustomField>
    <fullName>Championship__c</fullName>
    <description>Select championship</description>
    <inlineHelpText>Select championship</inlineHelpText>
    <label>Championship</label>
    <referenceTo>Championship__c</referenceTo>
    <relationshipLabel>Racer Positions</relationshipLabel>
    <relationshipName>Championship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RacerAssignmentsHelper.cls
public with sharing class RacerAssignmentsHelper {
    
    public static void updateRacerPositionStatus(List<Racer_Position__c> onBeforeInsert){
        
        String waitingListStatus = 'Waiting List';
        String notificationDevName='RacerStatusNotification';
        String msgTittle='Add racer to waiting list';
        String msgBody='One more racer added to Waiting List. Check: ';
        List <Racer_Position__c> listOfInsertedRacer = new List<Racer_Position__c>();
        List <Championship__c>  champs = [ SELECT Name, Championship_Capacity__c FROM Championship__c ];
        List <Racer_Position__c> listToInsert = new  List <Racer_Position__c>();

        //Preparing notification
        PermissionSetAssignment user = [ SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name = 'Racer_Manager'];
        Set<String> addressee = new Set<String>();
        addressee.add(user.AssigneeId);
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        CustomNotificationType notificationType = [ SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName=:notificationDevName ];
        notification.setTitle(msgTittle);
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(user.Id);
        
        //Prepare Map with Racers for each Championatship
        Map <Championship__c, List <Racer_Position__c>> howMuchRacersInChamp = new Map <Championship__c, List <Racer_Position__c>>();
        for (Championship__c c : champs) {
            List<Racer_Position__c> racers = new List<Racer_Position__c>();
            for (Racer_Position__c r : [ SELECT Name, Championship__c  FROM Racer_Position__c ]) {
                if (c.Id==r.Championship__c) {
                    racers.add(r);
                }
            }
            howMuchRacersInChamp.put(c, racers);
        }
       
        
        //Compare Map with Racers and new Racer
        for(Racer_Position__c r:onBeforeInsert){
           for (Championship__c c : champs) {
           
                if (r.Championship__c==c.Id && howMuchRacersInChamp.get(c).size()+1>c.Championship_Capacity__c) {

                    r.Status__c = waitingListStatus;
                    listToInsert.add(r);
                    msgBody+=r.Name;
                    notification.setBody(msgBody);
                    notification.send(addressee);
                }
           }
        }

        if (listToInsert.size() > 0) {

            //insert listToInsert; 
        }     
        
    }
}