force-app/main/default/objects/Championship__c/Championship__c.object-meta.xml
<CustomObject>
    <description>Championship information</description>
    <label>Championship</label>
    <nameField>
        <label>Championship  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Championship__c/fields/Championship_Date__c.field-meta.xml
<CustomField>
    <fullName>Championship_Date__c</fullName>
    <description>Set Championship Date and time</description>
    <inlineHelpText>Set Championship Date and time</inlineHelpText>
    <label>Championship Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Racer__c/Racer__c.object-meta.xml
<CustomObject>
    <description>Racer members</description>
    <label>Racer</label>
    <nameField>
        <label>Racer Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer__c/fields/Years_in_Racing__c.field-meta.xml
<CustomField>
    <fullName>Years_in_Racing__c</fullName>
    <label>Years in Racing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/Racer_Position__c.object-meta.xml
<CustomObject>
    <description>Racer position on championship</description>
    <label>Racer Position</label>
    <nameField>
        <label>Racer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer_Position__c/fields/Championship__c.field-meta.xml
<CustomField>
    <fullName>Championship__c</fullName>
    <description>Select championship</description>
    <inlineHelpText>Select championship</inlineHelpText>
    <label>Championship</label>
    <referenceTo>Championship__c</referenceTo>
    <relationshipLabel>Racer Positions</relationshipLabel>
    <relationshipName>Championship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <description>Select racer</description>
    <inlineHelpText>Select racer</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Racer__c</referenceTo>
    <relationshipLabel>Racer Positions</relationshipLabel>
    <relationshipName>Racer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Starting_Position__c.field-meta.xml
<CustomField>
    <fullName>Starting_Position__c</fullName>
    <description>Starting position of the racer</description>
    <inlineHelpText>Set starting position</inlineHelpText>
    <label>Starting Position #</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ListController.cls
public with sharing class ListController {
    
    @AuraEnabled(cacheable=true)
    public static String  getRacerPosition(Decimal filterYear) {
       system.debug(filterYear+' -value');
       List<Racer_Position__c> racersPos = new List<Racer_Position__c>();
       
       if(filterYear==null){
            
            racersPos = [ SELECT  Name, Championship__r.Name, Championship__r.Championship_Date__c, 
            Racer__r.Name, Racer__r.Years_in_Racing__c, Status__c, Starting_position__c  
            FROM Racer_Position__c];
       }
       else{
            racersPos = [ SELECT  Name, Championship__r.Name, Championship__r.Championship_Date__c, 
            Racer__r.Name, Racer__r.Years_in_Racing__c, Status__c, Starting_position__c  
            FROM Racer_Position__c WHERE Racer__r.Years_in_Racing__c=:filterYear ];
       }
       /*List<Racer_Position__c> racersPos = [ SELECT  Name, Championship__r.Name, Championship__r.Championship_Date__c, 
       Racer__r.Name, Racer__r.Years_in_Racing__c, Status__c, Starting_position__c  
       FROM Racer_Position__c WHERE Racer__r.Years_in_Racing__c=:filterYear ];*/
        
        List<ListCommonObject> finalList = new List<ListCommonObject>();
        //finalList.clear();
        for (Racer_Position__c r : racersPos) {
       
            ListCommonObject lh = new ListCommonObject();
            lh.championatName=r.Championship__r.Name;
            lh.racerName=r.Racer__r.Name;
            lh.status=r.Status__c;
            lh.champDate=r.Championship__r.Championship_Date__c;
            lh.yearsInRacing = r.Racer__r.Years_in_Racing__c;
            finalList.add(lh);
        }
        
        system.debug(finalList);
        return JSON.serialize(finalList);
    }
}