force-app/main/default/objects/Championship__c/Championship__c.object-meta.xml
<CustomObject>
    <description>Championship information</description>
    <label>Championship</label>
    <nameField>
        <label>Championship  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Championship__c/fields/Championship_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Championship_Capacity__c</fullName>
    <label>Championship Capacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/Racer_Position__c.object-meta.xml
<CustomObject>
    <description>Racer position on championship</description>
    <label>Racer Position</label>
    <nameField>
        <label>Racer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racer Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer_Position__c/fields/Championship__c.field-meta.xml
<CustomField>
    <fullName>Championship__c</fullName>
    <description>Select championship</description>
    <inlineHelpText>Select championship</inlineHelpText>
    <label>Championship</label>
    <referenceTo>Championship__c</referenceTo>
    <relationshipLabel>Racer Positions</relationshipLabel>
    <relationshipName>Championship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Racer_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RacerPositionStatusHelper.cls
public with sharing class RacerPositionStatusHelper {
    
    public static void updateRacerPositionStatus(Map<Id, Racer_Position__c> racers) {
        
        String checkingStatus = 'Rejected';
        String serchingStatus = 'Waiting List';
       
        List <Racer_Position__c>  racersInWaiting = [ SELECT Name, Championship__c, Creation_Date__c FROM Racer_Position__c WHERE Status__c=:serchingStatus ORDER BY Creation_Date__c];
        List <Championship__c>  champs = [ SELECT Name, Championship_Capacity__c FROM Championship__c ];

        List<Racer_Position__c> rejectedRacers = new List<Racer_Position__c>();

        Map <Championship__c, List <Racer_Position__c>> howMuchRacersInChamp = new Map <Championship__c, List <Racer_Position__c>>();
        for (Championship__c c : champs) {
            List<Racer_Position__c> listOfRacers = new List<Racer_Position__c>();
            for (Racer_Position__c r : [ SELECT Name, Championship__c  FROM Racer_Position__c ]) {
                if (c.Id==r.Championship__c) {
                    listOfRacers.add(r);
                }
            }
            howMuchRacersInChamp.put(c, listOfRacers);
        }
        //System.debug('In wait: ' + racersInWaiting);

        List <Racer_Position__c> forUpdate = new List<Racer_Position__c>();
        
        for (Racer_Position__c waitingRacer : racersInWaiting) {
            for (Racer_Position__c rejected : racers.values()) {
                if(rejected.Status__c==checkingStatus && rejected.Championship__c==waitingRacer.Championship__c){
                    for (Championship__c c : champs) {
                        if(howMuchRacersInChamp.get(c).size()+1>c.Championship_Capacity__c){
                            waitingRacer.Status__c='Approved';
                            forUpdate.add(waitingRacer);
                            System.debug('RW '+ waitingRacer.Name);
                        }
                    }
                }
            }
        }
        update forUpdate;        
    }
    
}
 