force-app/main/default/objects/Racer__c/Racer__c.object-meta.xml
<CustomObject>
    <description>Racer members</description>
    <label>Racer</label>
    <nameField>
        <label>Racer Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Racer__c/fields/Racer_Status__c.field-meta.xml
<CustomField>
    <fullName>Racer_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Racer Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RacerStatusHelper.cls
public with sharing class RacerStatusHelper {
    
    public static void updateRacerStatus(Map<Id, Racer__c> racers) {

        
        PermissionSetAssignment user = [ SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name = 'Racer_Manager'];
        String notificationDevName='RacerStatusNotification';
        String msgTittle='Racer status';
        String msgBody='Racer status become not active: ';
        String recordUrl;
        Set<String> addressee = new Set<String>();
        addressee.add(user.AssigneeId);
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        CustomNotificationType notificationType = [ SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName=:notificationDevName ];
        notification.setTitle(msgTittle);
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(user.Id);

        for (Racer__c r : racers.values()) {
            if(!r.Racer_Status__c){
                recordUrl=URL.getSalesforceBaseUrl().toExternalForm()+'/'+r.Id;
                notification.setBody(msgBody+recordUrl);
                notification.send(addressee);

                //System.debug('My racers: '+r);
                //System.debug('My url val: '+recordUrl);
            }
            
        }
    }
}